build: false
clone_folder: c:\project

platform:
    - x86
    - x64

branches:
    only:
        - master

cache:
    - c:\php -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.0-nts-Win32-VC14-%platform%.zip
    - IF %PHP%==1 7z x php-7.0.0-nts-Win32-VC14-%platform%.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\project
    - composer update --prefer-source

test_script:
    - cd c:\project
    - vendor\bin\phpunit.bat
